apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node-app
    component: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
      deployment: node-deployment
  template:
    metadata:
      labels:
        app: node-app
        deployment: node-deployment
        component: web
    spec:
      containers:
        - name: node-app
          image: vinodhconnects/node-app-website:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 150m
              memory: 128Mi
            limits:
              cpu: 150m
              memory: 128Mi
